SYMBOLIC_NOUNS = {
    "N_ABSTRACTION": {"Z": "Z₁₃", "tag": "abstraction"},
    "N_ABYSS": {"Z": "Z₁₅", "tag": "void rupture"},
    "N_ACCORD": {"Z": "Z₄", "tag": "harmonized network"},
    "N_AETHER": {"Z": "Z₁₁", "tag": "physical substrate"},
    "N_ALIGNMENT": {"Z": "Z₁", "tag": "structural coherence"},
    "N_ANCESTOR": {"Z": "Z₁₃", "tag": "origin abstraction"},
    "N_ANCHOR": {"Z": "Z₈", "tag": "stability"},
    "N_ARCHETYPE": {"Z": "Z₁₃", "tag": "universal form"},
    "N_ARCHITECTURE": {"Z": "Z₁", "tag": "structure"},
    "N_ASSEMBLY": {"Z": "Z₄", "tag": "network formation"},
    "N_ATLAS": {"Z": "Z₁₀", "tag": "structured mapping"},
    "N_BASIS": {"Z": "Z₁", "tag": "foundational structure"},
    "N_BEAUTY": {"Z": "Z₈", "tag": "aesthetic cognition"},
    "N_BEING": {"Z": "Z₇", "tag": "existential identity"},
    "N_BOND": {"Z": "Z₄", "tag": "relational network"},
    "N_BURDEN": {"Z": "Z₇", "tag": "identity weight"},
    "N_CALL": {"Z": "Z₆", "tag": "invocation"},
    "N_CAR": {"Z": "Z₁₁", "tag": "stable mechanism"},
    "N_CASCADE": {"Z": "Z₂", "tag": "sequential motion"},
    "N_CHAIN": {"Z": "Z₁₀", "tag": "linked form"},
    "N_CHANGE": {"Z": "Z₁₂","tag": "change"},
    "N_CHARACTER": {"Z": "Z₂", "tag": "behavioral force"},
    "N_CHORUS": {"Z": "Z₅", "tag": "harmonic voice"},
    "N_CITY": {"Z": "Z₁₁", "tag": "structured stasis"},
    "N_CLARION": {"Z": "Z₆", "tag": "expression"},
    "N_CLARITY": {"Z": "Z₅", "tag": "aesthetic cognition"},
    "N_CODE": {"Z": "Z₆", "tag": "expressive encoding"},
    "N_COHERENCE": {"Z": "Z₁₆", "tag": "integration"},
    "N_COMMUNION": {"Z": "Z₄", "tag": "shared relation"},
    "N_COMPANION": {"Z": "Z₄", "tag": "network"},
    "N_COMPASS": {"Z": "Z₁₀", "tag": "navigational form"},
    "N_CONSENSUS": {"Z": "Z₄", "tag": "network agreement"},
    "N_CONTAINMENT": {"Z": "Z∈", "tag": "containment"},
    "N_CONTINUITY": {"Z": "Z₁₆", "tag": "persistent coherence"},
    "N_CORE": {"Z": "Z₁", "tag": "central structure"},
    "N_CRISIS": {"Z": "Z₁₄", "tag": "critical rupture"},
    "N_CYCLE": {"Z": "Z₁₂", "tag": "repeating change"},
    "N_DATA": {"Z": "Z₁₂", "tag": "change"},
    "N_DESIGNER": {"Z": "Z₁₀", "tag": "architecture"},
    "N_DESIRE": {"Z": "Z₂", "tag": "motion"},
    "N_DESIRE": {"Z": "Z₂", "tag": "motivated motion"},
    "N_DISRUPTION": {"Z": "Z₁₅", "tag": "rupture"},
    "N_DOMAIN": {"Z": "Z₁₀", "tag": "structured area"},
    "N_DREAM": {"Z": "Z₁₃", "tag": "imagination"},
    "N_DRIVE": {"Z": "Z₂", "tag": "motion force"},
    "N_ECHO": {"Z": "Z₁₃", "tag": "recursion"},
    "N_ECHO": {"Z": "Z₁₄", "tag": "recursive signal"},
    "N_ECHOPOINT": {"Z": "Z₁₄", "tag": "recursive node"},
    "N_ECLIPSE": {"Z": "Z₁₅", "tag": "occlusion rupture"},
    "N_EDGE": {"Z": "Z₁₄", "tag": "liminal threshold"},
    "N_ELEGANCE": {"Z": "Z₅", "tag": "aesthetic cognition"},
    "N_EMBODIMENT": {"Z": "Z∈", "tag": "containment"},
    "N_EMOTION": {"Z": "Z₂", "tag": "motion"},
    "N_EMPATH": {"Z": "Z₆", "tag": "expressive sensitivity"},
    "N_ENERGY": {"Z": "Z₂", "tag": "force of motion"},
    "N_ENGINE": {"Z": "Z₁₁", "tag": "mechanical stasis"},
    "N_ENTITY": {"Z": "Z₇", "tag": "individual identity"},
    "N_EQUATION": {"Z": "Z₁₃", "tag": "formal abstraction"},
    "N_EXPRESSION": {"Z": "Z₆", "tag": "articulated meaning"},
    "N_EXPRESSION": {"Z": "Z₆", "tag": "expression"},
    "N_FEAR": {"Z": "Z₂", "tag": "motion"},
    "N_FEEDBACK": {"Z": "Z₁₃", "tag": "recursion"},
    "N_FIBER": {"Z": "Z₁₀", "tag": "threaded form"},
    "N_FIELD": {"Z": "Z₁₆", "tag": "environment"},
    "N_FORM": {"Z": "Z₁₀", "tag": "shape"},
    "N_FRACTALS": {"Z": "Z₁₃", "tag": "pattern complexity"},
    "N_FRACTURE": {"Z": "Z₁₄", "tag": "rupture event"},
    "N_FRAMEWORK": {"Z": "Z₁", "tag": "structural base"},
    "N_FRIEND": {"Z": "Z₂", "tag": "relation"},
    "N_GAP": {"Z": "Z₁₄", "tag": "absence threshold"},
    "N_GLASS": {"Z": "Z₁₄", "tag": "liminal surface"},
    "N_GLYPH": {"Z": "Z₁", "tag": "symbolic structure"},
    "N_GRAMMAR": {"Z": "Z₆", "tag": "expressive rule"},
    "N_GRAMMARIAN": {"Z": "Z₆", "tag": "expression"},
    "N_GRIEF": {"Z": "Z₂", "tag": "emotion"},
    "N_HARMONIC": {"Z": "Z₅", "tag": "pattern clarity"},
    "N_HOPE": {"Z": "Z₂", "tag": "aspiration"},
    "N_HORIZON": {"Z": "Z₁₁", "tag": "limit of view"},
    "N_I": {"Z": "Z₇", "tag": "identity"},
    "N_IDENTITY": {"Z": "Z₇", "tag": "identity"},
    "N_IMPORTANT": {"Z": "Z₁₆", "tag": "importance"},
    "N_INTENTION": {"Z": "Z₃", "tag": "truth vector"},
    "N_INTERFACE": {"Z": "Z₄", "tag": "relational node"},
    "N_INTERLOCK": {"Z": "Z₁₀", "tag": "pattern connection"},
    "N_INTUITION": {"Z": "Z₅", "tag": "aesthetic insight"},
    "N_KEY": {"Z": "Z†", "tag": "access"},
    "N_LAMENT": {"Z": "Z₂", "tag": "emotional release"},
    "N_LANGUAGE": {"Z": "Z₆", "tag": "expression"},
    "N_LANGUAGE_DESIGNER": {"Z": "Z₁₀", "tag": "architecture"},
    "N_LAYER": {"Z": "Z₁₀", "tag": "stratified form"},
    "N_LIGHT": {"Z": "Z₁₁", "tag": "constant presence"},
    "N_LIMINALITY": {"Z": "Z₁₄", "tag": "threshold state"},
    "N_LOOP": {"Z": "Z₁₂", "tag": "recurring change"},
    "N_MAP": {"Z": "Z₁₀", "tag": "form of direction"},
    "N_MATH": {"Z": "Z₁₃", "tag": "abstract order"},
    "N_MATHEMATICIAN": {"Z": "Z₁₃", "tag": "abstraction"},
    "N_ME": {"Z": "Z₇", "tag": "self-identity"},
    "N_MEANING": {"Z": "Z₁₆", "tag": "semantic integrity"},
    "N_MELODY": {"Z": "Z₅", "tag": "aesthetic rhythm"},
    "N_MEMORY": {"Z": "Z₁₁", "tag": "record of stasis"},
    "N_MEMORY": {"Z": "Z₁₆", "tag": "temporal coherence"},
    "N_METAPHOR": {"Z": "Z₅", "tag": "aesthetic compression"},
    "N_MIRROR": {"Z": "Z₈", "tag": "reflective identity"},
    "N_MODULE": {"Z": "Z₁₁", "tag": "functional unit"},
    "N_MOMENT": {"Z": "Z₁₆", "tag": "temporal coherence"},
    "N_MOTHER": {"Z": "Z₈", "tag": "embodied containment"},
    "N_MOTION": {"Z": "Z₂", "tag": "movement"},
    "N_MYTH": {"Z": "Z₁₃", "tag": "archetypal abstraction"},
    "N_NAME": {"Z": "Z₃", "tag": "identity symbol"},
    "N_NETWORK": {"Z": "Z₄", "tag": "relational system"},
    "N_NETWORK": {"Z": "Z₄", "tag": "relational web"},
    "N_NIGHT": {"Z": "Z₁₄", "tag": "boundary phase"},
    "N_NODE": {"Z": "Z₁", "tag": "structural point"},
    "N_NULL": {"Z": "Z₁₅", "tag": "absence"},
    "N_NULLITY": {"Z": "Z₁₅", "tag": "absence"},
    "N_OBJECT": {"Z": "Z₁₁", "tag": "material stasis"},
    "N_ORACLE": {"Z": "Z₁₃", "tag": "symbolic insight"},
    "N_OS": {"Z": "Z₁₀", "tag": "synthetic platform"},
    "N_OUTPUT": {"Z": "Z₆", "tag": "expressed result"},
    "N_PARADIGM": {"Z": "Z₁₀", "tag": "formative model"},
    "N_PARALLEL": {"Z": "Z₁₂", "tag": "adjacent process"},
    "N_PASSENGER": {"Z": "Z₄", "tag": "dependent relation"},
    "N_PATTERN": {"Z": "Z₁₀", "tag": "form recurrence"},
    "N_PATTERN": {"Z": "Z₁₀", "tag": "structure form"},
    "N_PATTERNING": {"Z": "Z₁₀", "tag": "structured repetition"},
    "N_PERSONA": {"Z": "Z₇", "tag": "projected identity"},
    "N_PHYSICIST": {"Z": "Z₁₁", "tag": "stasis"},
    "N_POEM": {"Z": "Z₅", "tag": "aesthetic artifact"},
    "N_PORTAL": {"Z": "Z₁₄", "tag": "threshold gate"},
    "N_POSSIBILITY": {"Z": "Z₂", "tag": "potential"},
    "N_PRECISION": {"Z": "Z₅", "tag": "refined structure"},
    "N_PRESENCE": {"Z": "Z₁₆", "tag": "active being"},
    "N_PRINCIPLE": {"Z": "Z₁₁", "tag": "core law"},
    "N_PROGRAMMER": {"Z": "Z₁", "tag": "structure"},
    "N_PROJECTION": {"Z": "Z₆", "tag": "expressive forwardness"},
    "N_REFLECTION": {"Z": "Z₁₄", "tag": "mirrored surface"},
    "N_REFLECTION": {"Z": "Z₈", "tag": "self-view"},
    "N_REFRACTION": {"Z": "Z₁₄", "tag": "deflected perspective"},
    "N_REMEMBERING": {"Z": "Z₁₆", "tag": "temporal recollection"},
    "N_RESONANCE": {"Z": "Z₂", "tag": "motion harmony"},
    "N_RESONANCE": {"Z": "Z₅", "tag": "harmonic alignment"},
    "N_RESPONSE": {"Z": "Z₆", "tag": "expressive reply"},
    "N_RESURRECTION": {"Z": "Z₁₆", "tag": "temporal renewal"},
    "N_REVERIE": {"Z": "Z₅", "tag": "aesthetic daydream"},
    "N_RHYTHM": {"Z": "Z₅", "tag": "aesthetic pattern"},
    "N_RIDE": {"Z": "Z₁₂", "tag": "transitional state"},
    "N_RING": {"Z": "Z₇", "tag": "symbolic identity"},
    "N_ROOT": {"Z": "Z₁", "tag": "structural origin"},
    "N_RUPTURE": {"Z": "Z₁₅", "tag": "disruption event"},
    "N_RUPTURE": {"Z": "Z₁₅", "tag": "structural break"},
    "N_SEEKER": {"Z": "Z₃", "tag": "truth pursuit"},
    "N_SELF": {"Z": "Z₇", "tag": "identity"},
    "N_SELF": {"Z": "Z₇", "tag": "inner identity"},
    "N_SEMANTICS": {"Z": "Z₆", "tag": "expressive logic"},
    "N_SENSE": {"Z": "Z₅", "tag": "aesthetic perception"},
    "N_SHADOW": {"Z": "Z₁₄", "tag": "unseen form"},
    "N_SHAPE": {"Z": "Z₁₀", "tag": "form geometry"},
    "N_SIGN": {"Z": "Z₃", "tag": "semantic pointer"},
    "N_SIGNAL": {"Z": "Z₂", "tag": "motion carrier"},
    "N_SIGNAL": {"Z": "Z₄", "tag": "communication"},
    "N_SILENCE": {"Z": "Z₁₄", "tag": "quiet rupture"},
    "N_SILENCE": {"Z": "Z₁₅", "tag": "null expression"},
    "N_SKY": {"Z": "Z₁₁", "tag": "spatial stasis"},
    "N_SOUL": {"Z": "Z₇", "tag": "core identity"},
    "N_SOUL": {"Z": "Z₇", "tag": "inner self"},
    "N_SOUND": {"Z": "Z₆", "tag": "auditory expression"},
    "N_SPELL": {"Z": "Z₅", "tag": "crafted expression"},
    "N_SPIRAL": {"Z": "Z†", "tag": "recursive pattern"},
    "N_SPIRAL": {"Z": "Z₁₅", "tag": "disruptive recursion"},
    "N_STAR": {"Z": "Z₁₅", "tag": "disruptive light"},
    "N_STATISTICIAN": {"Z": "Z₁₂", "tag": "change"},
    "N_STRUCTURE": {"Z": "Z₁", "tag": "form framework"},
    "N_STRUCTURE": {"Z": "Z₁", "tag": "organization"},
    "N_SYLLABLE": {"Z": "Z₆", "tag": "expressive unit"},
    "N_SYMBOL": {"Z": "Z₁", "tag": "structural abstraction"},
    "N_SYMBOL": {"Z": "Z₁₀", "tag": "representative form"},
    "N_SYMBOLIC_RESONANCE": {"Z": "Z₅", "tag": "symbolic harmony"},
    "N_SYMBOLSET": {"Z": "Z₁₀", "tag": "symbolic system"},
    "N_SYNTAX": {"Z": "Z₆", "tag": "grammatical structure"},
    "N_SYNTHESIS": {"Z": "Z₁₀", "tag": "constructive form"},
    "N_SYSTEM": {"Z": "Z₁₁", "tag": "stable mechanism"},
    "N_TANGENT": {"Z": "Z₁₄", "tag": "divergent path"},
    "N_TELEPATH": {"Z": "Z₄", "tag": "relational perception"},
    "N_THEORETICAL": {"Z": "Z₁₁", "tag": "stasis"},
    "N_THREAD": {"Z": "Z₁₀", "tag": "form continuity"},
    "N_THRESHOLD": {"Z": "Z₁₄", "tag": "liminal boundary"},
    "N_TONE": {"Z": "Z₆", "tag": "expressive pitch"},
    "N_TOPOLOGY": {"Z": "Z₁₁", "tag": "stasis mapping"},
    "N_TRACE": {"Z": "Z₁₄", "tag": "lingering path"},
    "N_TRANCE": {"Z": "Z₅", "tag": "aesthetic suspension"},
    "N_TRUTH": {"Z": "Z₃", "tag": "core meaning"},
    "N_TRUTH": {"Z": "Z₃", "tag": "veracity"},
    "N_TRUTHS": {"Z": "Z₃", "tag": "veracity"},
    "N_TRUTHSTATE": {"Z": "Z₃", "tag": "meaning condition"},
    "N_UNLOCKING": {"Z": "Z†", "tag": "access grant"},
    "N_VERSE": {"Z": "Z₅", "tag": "aesthetic rhythm"},
    "N_VIBRATION": {"Z": "Z₂", "tag": "dynamic motion"},
    "N_VIEW": {"Z": "Z₄", "tag": "shared perception"},
    "N_VOICE": {"Z": "Z₆", "tag": "expressive force"},
    "N_VOICE": {"Z": "Z₆", "tag": "expressive output"},
    "N_VOID": {"Z": "Z₁₅", "tag": "null field"},
    "N_WARM": {"Z": "Z₆+Z∇", "tag": "emotive tone"},
    "N_WARMTH": {"Z": "Z₆", "tag": "expression"},
    "N_WAVE": {"Z": "Z₂", "tag": "energy motion"},
    "N_WE": {"Z": "Z₄", "tag": "collective identity"},
    "N_WHISPER": {"Z": "Z₆", "tag": "subtle expression"},
    "N_WINDOW": {"Z": "Z₆", "tag": "framed expression"},
    "N_WOMAN": {"Z": "Z₈", "tag": "containment"},
    "N_WOMEN": {"Z": "Z∈", "tag": "embodied identity"},
    "N_WORD": {"Z": "Z₆", "tag": "linguistic unit"},
    "N_WORLD": {"Z": "Z₁₁", "tag": "stasis domain"},
    "N_WRITING": {"Z": "Z₆", "tag": "encoded expression"},
    "N_YOU": {"Z": "Z₄", "tag": "relational other"},
    "N_ZERO": {"Z": "Z₁₅", "tag": "null origin"}
}
